    conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'black',
    default_shade_color = 'black',
    color1 = '#32cd32', -- Green
    color2 = '#1e90ff', -- Blue
    color3 = '#ffa500', -- Orange
    color4 = '#9a9d9f', -- Light Gray
    color5 = '#ff0000', -- Red
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'Cantarell:size=8',
    gap_x = 5,
    gap_y = 0,
    minimum_height = 1080,
    minimum_width = 80,
    net_avg_samples = 2,
    no_buffers = true,
    double_buffer = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    --own_window_colour = '#151515',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_type = 'normal',
    own_window_class = 'Conky',
    own_window_hints = "undecorated,below,sticky,skip_taskbar,skip_pager",
    stippled_borders = 0,
    update_interval = 60.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false,
    lua_load = '/home/stu/Pickles-Weather/Pickles-Weather/weather.lua' ,
    }

conky.text = [[
${font Cantarell:size=16}${alignc}${USER}${font}
${alignc}Testing
${alignc} ${font weight:bold}Pickles-Weather${font}
Example use of weather.lua
1
=============================================
it is currently ${lua conky_temperature}°c with ${lua conky_description}

with a minimum of ${lua conky_min}°c and a maximum of ${lua conky_max}°c

=============================================
Example
2
=============================================
${alignc}${color purple} ${font weight:bold}Todays Weather${font weight:regular}
${color blue}Current Temp: ${goto 170}${color red}${lua conky_temperature}°c  ${lua_parse conky_image p=215,225}
${color blue}Current Conditions: ${goto 170}${color red}${lua conky_description}
${color blue}Todays min/max: ${goto 170}${color pink}${lua conky_min}°c${color}/${color red}${lua conky_max}°c
${color}
=============================================
Example
3
=============================================
${color2}${lua_parse conky_image p=165,410}Temperature: ${lua conky_temperature}°C
Min: ${lua conky_min}°C
Max: ${lua conky_max}°C
Description: ${lua conky_description}${color}
=============================================

]]
